### ISSUE TITLE
Which clients has this been tested with?

### ISSUE THREAD

**Issue by voxpelli** [sedenardi/node-caldav-adapter#1]
Very excited to someone work on a project like this! I have often thought of building something on top of Caldav, but never had the time to read up on the protocol.

How far have you gotten in the implementation? Does it work with eg. Apple's Calendar app or with eg. Google's? Or is the support yet more basic than that?

Anything you would need help with?

**Comment by sedenardi** [comment]
Hi there, thanks for your interest. I definitely need to add to the documentation the info you've asked about.

For the current stable version:
- Creating, updating, and deleting one-off (not recurring) events work.
- Calendars can be declared read-only or writable.
- Calendars themselves aren't editable currently (i.e. changing the title, color)
- Timezones aren't utilized, everything is in UTC (see next section for why this is changing).
- Tested it with MacOS Calendar.app as well as iOS (most apps use their system service, tested with the Apple Calendar and Google Calendar apps), and Mozilla Thunderbird (via the Lightning plugin), though Mozilla support isn't high priority.

My immediate roadmap includes (v2):
- Support recurring events. This is almost done, but I'm waiting on one of the project's dependencies `ical-generator` to add support for the `RECURRENCE-ID` field (I submitted a PR).
- Move from using UNIX timestamps to ISO timestamps. I initially used UNIX timestamp because that's what my company's time is kept in, but it doesn't make sense once you start talking about recurring events. This is done.
- Test with Android
- Better documentation

My future roadmap includes:
- Adding tests (integration tests with a dummy CalDAV client) 
- Add scheduling support (inbox/outbox calendars, defined in the [RFC here](https://tools.ietf.org/html/rfc6638)
- Add support for Express and other frameworks

Since the recurring event and ISO timestamp stuff significantly changes the API, I want to get that out of the way before I start adding tests. If porting to other frameworks, like Express,

**Comment by sedenardi** [comment]
Closing this for now. I've updated the README with the clients tested with (as well as a ton of other documentation).
